<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    version="1.1"
    viewbox="0 0 18 18"
    style="
      shape-rendering: geometricPrecision;
      text-rendering: geometricPrecision;
      image-rendering: optimizeQuality;
      fill-rule: evenodd;
      clip-rule: evenodd;
    "
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <rect
      class="ql-stroke"
      height="12"
      width="12"
      x="3"
      y="3"
    ></rect>
    <rect
      class="ql-fill"
      height="12"
      width="1"
      x="5"
      y="3"
    ></rect>
    <rect
      class="ql-fill"
      height="12"
      width="1"
      x="12"
      y="3"
    ></rect>
    <rect
      class="ql-fill"
      height="2"
      width="8"
      x="5"
      y="8"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="3"
      y="5"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="3"
      y="7"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="3"
      y="10"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="3"
      y="12"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="12"
      y="5"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="12"
      y="7"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="12"
      y="10"
    ></rect>
    <rect
      class="ql-fill"
      height="1"
      width="3"
      x="12"
      y="12"
    ></rect>
  </svg>
</template>
